BeatclicSite/Models/ErrorViewModel.cs
using System;

namespace BeatclicSite.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BeatclicSite/Models/Offre.cs
using System;

namespace BeatclicSite.Models
{
    public class Offre
    {
        private string titre;
        private string url;
        private int prix;

        public Offre()
        {
            titre = url = String.Empty;
        }
        public Offre(string titre, string url, int prix)
        {
            this.titre = titre;
            this.url = url;
            if(this.prix < 0)
            {
                throw new ArgumentOutOfRangeException(
                    nameof(prix), 
                    "Le prix ne peux etre inferieure a 0 euro"
                );
            }
            this.prix = prix;
        }
        public void AugmenterLesPrix()
        {
            prix ++;
        }
        public string GetTitre()
        {
            return titre;
        }
        public string GetTitre2() => titre;
        public string Titre
        {
            get
            {
                return titre;
            }
            set
            {
                if(value.Length<2)
                {
                    throw new ArgumentException("Titre trop court");
                }
                titre = value;
            }
        }

        public int Prix
        {
            get => prix;
        }

        public string UrlHttps
        {
            get { return $"https://{url}"; }
        }
    }
}

BeatclicSite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BeatclicSite.Models;

namespace BeatclicSite.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

BeatclicSite/Controllers/OffreController.cs
using System.Collections.Generic;
using BeatclicSite.Models;
using Microsoft.AspNetCore.Mvc;

namespace BeatclicSite.Controllers
{
    public class OffreController : Controller
    {
        public IActionResult Index()
        {
            var galerie = new List<Offre>()
            {
                new Offre(titre:"Koba / RR 9.1", url:"static.booska-p.com/images/news/niska-et-koba-rr-9-1-20h-videoclip-649.jpg", prix: 20),
                new Offre(titre:"niska / batimemt", url:"media.gqmagazine.fr/photos/5d710f4a0113f500080af79e/master/pass/niska%20_%20KORIA%201%20.png", prix: 15),
                new Offre(titre:"SCH HAMZA / HS", url:"static.booska-p.com/images/news/niska-et-koba-rr-9-1-20h-videoclip-649.jpg", prix: 13),
            };
            for(var i=0; i<galerie.Count; i++)
            {
                galerie[i].AugmenterLesPrix();
            }
            foreach(var photo in galerie)
            {
                photo.AugmenterLesPrix();
            }
            return View(galerie);
        }
    }
}

BeatclicSite/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BeatclicSite/Views/Offre/Index.cshtml
@model IEnumerable<BeatclicSite.Models.Offre>

@{
    ViewData["Title"] = "Galerie";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>
    <a asp-action="Index" asp-controller="Home">Revenir à l'accueil (bien)</a>
    <a href="/Home/Index">Revenir à l'accueil (pas bien)</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Titre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UrlHttps)
        </th>
        @Html.DisplayNameFor(model => model.Prix)
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UrlHttps)
            </td>
            <td>
                <img src="@item.UrlHttps" alt="@Html.DisplayFor(modelItem => item.Titre)" /></td>
        </tr>
        
    }
    </tbody>
</table>

BeatclicSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BeatclicSite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BeatclicSite</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Offre" asp-action="Index">Beatclic</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - BeatclicSite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>